name: Electron CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    container:
      image: node:latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: npm install -g typescript
           | npm install
           | echo "test"
    - name: Build
      run: tsc
    - name: lint
      run: npm run lint
    - name: test
      run: npm test

