name: Electron CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    container:
      image: node:latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: npm install
    - name: Build
      run: npx tsc
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test

